export const apiPaths = {
  auth: {
    login: '/api/v1/Auth/login',
    refresh: '/api/v1/Auth/refresh',
    logout: '/api/v1/Auth/logout',
  },
  clientes: {
    base: '/api/v1/Clientes',
    pf: '/api/v1/ClientePfs',
    pj: '/api/v1/ClientePjs',
    origens: '/api/v1/ClienteOrigens',
    lgpd: '/api/v1/ClienteLgpdConsentimentos',
    indicacoes: '/api/v1/ClienteIndicacoes',
    financeiros: '/api/v1/ClienteFinanceiros',
    enderecos: '/api/v1/ClienteEnderecos',
    documentos: '/api/v1/ClienteDocumentos',
    contatos: '/api/v1/ClienteContatos',
    anexos: '/api/v1/ClienteAnexos',
    table:'/api/v1/Clientes/table',
  },
  veiculos: {
    base: '/api/v1/Veiculos',
    marcas: '/api/v1/VeiculoMarcas',
    modelos: '/api/v1/VeiculoModelos',
  },
  fornecedores: {
    base: '/api/v1/Fornecedores',
    segmentos: '/api/v1/FornecedorSegmentos',
    segmentosRel: '/api/v1/FornecedorSegmentosRel',
    enderecos: '/api/v1/FornecedorEnderecos',
    contatos: '/api/v1/FornecedorContatos',
    representantes: '/api/v1/FornecedorRepresentantes',
    bancos: '/api/v1/FornecedorBancos',
    documentos: '/api/v1/FornecedorDocumentos',
    certificacoes: '/api/v1/FornecedorCertificacoes',
    avaliacoes: '/api/v1/FornecedorAvaliacoes',
  },
  mecanicos: {
    base: '/api/v1/Mecanicos',
    especialidades: '/api/v1/MecanicoEspecialidades',
    especialidadesRel: '/api/v1/MecanicoEspecialidadeRel',
    certificacoes: '/api/v1/MecanicoCertificacoes',
    contatos: '/api/v1/MecanicoContatos',
    disponibilidades: '/api/v1/MecanicoDisponibilidades',
    documentos: '/api/v1/MecanicoDocumentos',
    enderecos: '/api/v1/MecanicoEnderecos',
    experiencias: '/api/v1/MecanicoExperiencias',
  },
  ordens: {
    base: '/api/v1/OrdemServicos',
    pagamentos: '/api/v1/OrdemServicoPagamentos',
    observacoes: '/api/v1/OrdemServicoObservacoes',
    itens: '/api/v1/OrdemServicoItens',
    historicos: '/api/v1/OrdemServicoHistoricos',
    checklists: '/api/v1/OrdemServicoChecklists',
    avaliacoes: '/api/v1/OrdemServicoAvaliacoes',
    anexos: '/api/v1/OrdemServicoAnexos',
  },
  estoque: {
    categorias: '/api/v1/EstoqueCategorias',
    fabricantes: '/api/v1/EstoqueFabricantes',
    localizacoes: '/api/v1/EstoqueLocalizacoes',
    pecas: '/api/v1/EstoquePecas',
    movimentacoes: '/api/v1/EstoqueMovimentacoes',
    anexos: '/api/v1/EstoquePecaAnexos',
    fornecedores: '/api/v1/EstoquePecaFornecedores',
    historicos: '/api/v1/EstoquePecaHistoricos',
  },
  financeiro: {
    metodos: '/api/v1/FinanceiroMetodosPagamento',
    pagamentos: '/api/v1/FinanceiroPagamentos',
    anexos: '/api/v1/FinanceiroAnexos',
    pagar: '/api/v1/FinanceiroContasPagar',
    receber: '/api/v1/FinanceiroContasReceber',
    historicos: '/api/v1/FinanceiroHistoricos',
    lancamentos: '/api/v1/FinanceiroLancamentos',
  },
};
